"use client";
import HeroNavbar from "@/components/HeroNavbar/HeroNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";
import Providers from "@/Store/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>

      <body>
        <div class="container-fluid">
          <nav class="navbar fixed-top navbar-expand-lg navbar-light main_navbar">
            <div class="container">
              <img
                src="https://shohagh.com/assets/img/logo-sp2.png"
                width="250"
                alt="logo"
              />
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item me-3">
                    <Link
                      href="/"
                      className={
                        pathname === "/"
                          ? "m-0 p-0 button_active_color text-decoration-none border-bottom border-danger"
                          : "m-0 p-0 text-decoration-none"
                      }
                    >
                      Home
                    </Link>
                  </li>
                  {/* <li class="nav-item dropdown">
                    <Link
                      class="nav-link dropdown-toggle mt-0 pt-0 me-3 text-primary"
                      href="#"
                      id="navbarDropdown"
                      role="button"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                    >
                      Account
                    </Link>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li>
                        <Link class="dropdown-item" href="/update_profile">
                          Edit Profile
                        </Link>
                      </li>
                      <li>
                        <Link class="dropdown-item" href="/change_password">
                          Change Profile
                        </Link>
                      </li>
                    </ul>
                  </li> */}
                  <li class="nav-item me-3">
                    <Link
                      href="/locations"
                      className={
                        pathname === "/locations"
                          ? "m-0 p-0 button_active_color text-decoration-none border-bottom border-danger"
                          : "m-0 p-0 text-decoration-none"
                      }
                    >
                      Locations
                    </Link>
                  </li>
                  <li class="nav-item me-3">
                    <Link
                      href="/contactUs"
                      className={
                        pathname === "/contactUs"
                          ? "m-0 p-0 button_active_color text-decoration-none border-bottom border-danger"
                          : "m-0 p-0 text-decoration-none"
                      }
                    >
                      Contact Us
                    </Link>
                  </li>
                  <li class="nav-item me-3">
                    <Link
                      href="/faq"
                      className={
                        pathname === "/faq"
                          ? "m-0 p-0 button_active_color text-decoration-none border-bottom border-danger"
                          : "m-0 p-0 text-decoration-none"
                      }
                    >
                      FAQ
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
        <Providers>{children}</Providers>

        <Footer></Footer>

        <script
          src="https://kit.fontawesome.com/eb8a4c75b0.js"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
          crossOrigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
          crossOrigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
